### ISSUE TITLE
permission required: READ_PHONE_STATE 

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-gateway#103]
On some phones, sending a multipart unicode message fails with style:

```
I/MedicGateway(17355): java.lang.SecurityException: Requires READ_PHONE_STATE: Neither user 10096 nor current process has android.permission.READ_PHONE_STATE..
I/MedicGateway(17355):  at android.os.Parcel.readException(Parcel.java:1549)
I/MedicGateway(17355):  at android.os.Parcel.readException(Parcel.java:1502)
I/MedicGateway(17355):  at com.android.internal.telephony.IPhoneSubInfo$Stub$Proxy.getGroupIdLevel1(IPhoneSubInfo.java:556)
I/MedicGateway(17355):  at android.telephony.TelephonyManager.getGroupIdLevel1(TelephonyManager.java:1917)
I/MedicGateway(17355):  at android.telephony.SmsMessage.hasEmsSupport(SmsMessage.java:812)
I/MedicGateway(17355):  at com.android.internal.telephony.gsm.SmsMessage.calculateLength(SmsMessage.java:851)
I/MedicGateway(17355):  at android.telephony.SmsMessage.fragmentText(SmsMessage.java:338)
I/MedicGateway(17355):  at android.telephony.SmsMessage.fragmentText(SmsMessage.java:924)
I/MedicGateway(17355):  at android.telephony.SmsManager.divideMessage(SmsManager.java:340)
I/MedicGateway(17355):  at medic.gateway.alert.WakefulService.a(Unknown Source)
I/MedicGateway(17355):  at com.commonsware.cwac.wakeful.a.onHandleIntent(Unknown Source)
I/MedicGateway(17355):  at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
I/MedicGateway(17355):  at android.os.Handler.dispatchMessage(Handler.java:102)
I/MedicGateway(17355):  at android.os.Looper.loop(Looper.java:135)
I/MedicGateway(17355):  at android.os.HandlerThread.run(HandlerThread.java:61)
 ```

Seen on Huawei Gplay Mini.  cc @bishwas-medic @ashish-medic

**Comment by alxndrsn** [comment]
Related to this?

```
    public static boolean  [More ...] hasEmsSupport() {
        if (!isNoEmsSupportConfigListExisted()) {
            return true;
        }
        String simOperator;
        String gid;
        final long identity = Binder.clearCallingIdentity();
        try {
            simOperator = TelephonyManager.getDefault().getSimOperatorNumeric();
            gid = TelephonyManager.getDefault().getGroupIdLevel1();
        } finally {
            Binder.restoreCallingIdentity(identity);
        }

        for (NoEmsSupportConfig currentConfig : mNoEmsSupportConfigList) {
            if (simOperator.startsWith(currentConfig.mOperatorNumber) &&
                (TextUtils.isEmpty(currentConfig.mGid1) ||
                (!TextUtils.isEmpty(currentConfig.mGid1)
                && currentConfig.mGid1.equalsIgnoreCase(gid)))) {
                return false;
            }
         }

        return true;
    }
```
in `android.telephony.SmsMessage`

The existance of `hasEmsSupport()` implies that we shouldn't need our CDMA compat mode...

**Comment by alxndrsn** [comment]
> The existance of `hasEmsSupport()` implies that we shouldn't need our CDMA compat mode...

... or not:

```
                 if (!android.telephony.SmsMessage.hasEmsSupport()) {
                     // make sure total number of segments is less than 10
                     if (octets <= 9 * (max_user_data_bytes_with_header - 2))
                         max_user_data_bytes_with_header -= 2;
                 }
```
