### ISSUE TITLE
com.android.builder.testing.api.DeviceException: No connected devices!

### ISSUE THREAD

**Issue by mandric** [medic/medic-gateway#2]
Can we have a `make` that just builds the software and a `make test` that runs the tests?

```
mandric in ~/dev/medic-gateway 
$ make
rm -rf src/main/assets/
rm -rf build/
./gradlew --daemon --parallel --stacktrace installDebug
Downloading https://services.gradle.org/distributions/gradle-2.13-bin.zip
..................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Unzipping /Users/mandric/.gradle/wrapper/dists/gradle-2.13-bin/4xsgxlfjcxvrea7akf941nvc7/gradle-2.13-bin.zip to /Users/mandric/.gradle/wrapper/dists/gradle-2.13-bin/4xsgxlfjcxvrea7akf941nvc7
Set executable permissions for: /Users/mandric/.gradle/wrapper/dists/gradle-2.13-bin/4xsgxlfjcxvrea7akf941nvc7/gradle-2.13/bin/gradle
Starting a new Gradle Daemon for this build (subsequent builds will be faster).
Parallel execution is an incubating feature.
Download https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.1.0/gradle-2.1.0.pom
Download https://jitpack.io/com/github/alxndrsn/android-check/1f87548c0686d823e5f1490a2053b70bd9f5022e/android-check-1f87548c0686d823e5f1490a2053b70bd9f5022e.pom
Download https://repo1.maven.org/maven2/com/trickyandroid/jacoco-everywhere/0.2.1/jacoco-everywhere-0.2.1.pom
Download https://repo1.maven.org/maven2/com/android/tools/build/gradle-core/2.1.0/gradle-core-2.1.0.pom
Download https://repo1.maven.org/maven2/com/puppycrawl/tools/checkstyle/6.10.1/checkstyle-6.10.1.pom
Download https://repo1.maven.org/maven2/com/google/code/findbugs/findbugs/3.0.1/findbugs-3.0.1.pom
Download https://repo1.maven.org/maven2/net/sourceforge/pmd/pmd-java/5.3.4/pmd-java-5.3.4.pom
Download https://repo1.maven.org/maven2/net/sourceforge/pmd/pmd/5.3.4/pmd-5.3.4.pom
Download https://repo1.maven.org/maven2/com/android/tools/build/builder/2.1.0/builder-2.1.0.pom
Download https://repo1.maven.org/maven2/com/android/tools/lint/lint/25.1.0/lint-25.1.0.pom
Download https://repo1.maven.org/maven2/com/android/tools/build/transform-api/2.0.0-deprecated-use-gradle-api/transform-api-2.0.0-deprecated-use-gradle-api.pom
Download https://repo1.maven.org/maven2/com/android/tools/build/gradle-api/2.1.0/gradle-api-2.1.0.pom
Download https://repo1.maven.org/maven2/com/android/databinding/compilerCommon/2.1.0/compilerCommon-2.1.0.pom
Download https://repo1.maven.org/maven2/org/jacoco/org.jacoco.core/0.7.2.201409121644/org.jacoco.core-0.7.2.201409121644.pom
Download https://repo1.maven.org/maven2/org/jacoco/org.jacoco.build/0.7.2.201409121644/org.jacoco.build-0.7.2.201409121644.pom
Download https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.pom
Download https://repo1.maven.org/maven2/org/apache/commons/commons-parent/37/commons-parent-37.pom
Download https://repo1.maven.org/maven2/org/apache/apache/16/apache-16.pom
Download https://repo1.maven.org/maven2/antlr/antlr/2.7.7/antlr-2.7.7.pom
Download https://repo1.maven.org/maven2/org/antlr/antlr4-runtime/4.5.1-1/antlr4-runtime-4.5.1-1.pom
Download https://repo1.maven.org/maven2/org/antlr/antlr4-master/4.5.1-1/antlr4-master-4.5.1-1.pom
Download https://repo1.maven.org/maven2/commons-beanutils/commons-beanutils/1.9.2/commons-beanutils-1.9.2.pom
Download https://repo1.maven.org/maven2/commons-cli/commons-cli/1.3.1/commons-cli-1.3.1.pom
Download https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/2.0.1/jsr305-2.0.1.pom
Download https://repo1.maven.org/maven2/com/google/code/findbugs/bcel-findbugs/6.0/bcel-findbugs-6.0.pom
Download https://repo1.maven.org/maven2/com/google/code/findbugs/jFormatString/2.0.1/jFormatString-2.0.1.pom
Download https://repo1.maven.org/maven2/org/ow2/asm/asm-debug-all/5.0.2/asm-debug-all-5.0.2.pom
Download https://repo1.maven.org/maven2/org/ow2/asm/asm-parent/5.0.2/asm-parent-5.0.2.pom
Download https://repo1.maven.org/maven2/com/apple/AppleJavaExtensions/1.4/AppleJavaExtensions-1.4.pom
Download https://repo1.maven.org/maven2/jaxen/jaxen/1.1.6/jaxen-1.1.6.pom
Download https://repo1.maven.org/maven2/net/java/dev/javacc/javacc/5.0/javacc-5.0.pom
Download https://repo1.maven.org/maven2/net/sourceforge/pmd/pmd-core/5.3.4/pmd-core-5.3.4.pom
Download https://repo1.maven.org/maven2/net/sourceforge/saxon/saxon/9.1.0.8/saxon-9.1.0.8.pom
Download https://repo1.maven.org/maven2/com/android/tools/build/builder-model/2.1.0/builder-model-2.1.0.pom
Download https://repo1.maven.org/maven2/com/android/tools/build/builder-test-api/2.1.0/builder-test-api-2.1.0.pom
Download https://repo1.maven.org/maven2/com/android/tools/sdklib/25.1.0/sdklib-25.1.0.pom
Download https://repo1.maven.org/maven2/com/android/tools/sdk-common/25.1.0/sdk-common-25.1.0.pom
Download https://repo1.maven.org/maven2/com/android/tools/common/25.1.0/common-25.1.0.pom
Download https://repo1.maven.org/maven2/com/android/tools/build/manifest-merger/25.1.0/manifest-merger-25.1.0.pom
Download https://repo1.maven.org/maven2/com/android/tools/ddms/ddmlib/25.1.0/ddmlib-25.1.0.pom
Download https://repo1.maven.org/maven2/com/android/tools/jack/jack-api/0.10.0/jack-api-0.10.0.pom
Download https://repo1.maven.org/maven2/com/android/tools/jill/jill-api/0.10.0/jill-api-0.10.0.pom
Download https://repo1.maven.org/maven2/com/android/tools/lint/lint-checks/25.1.0/lint-checks-25.1.0.pom
Download https://repo1.maven.org/maven2/com/android/tools/annotations/25.1.0/annotations-25.1.0.pom
Download https://repo1.maven.org/maven2/com/android/databinding/baseLibrary/2.1.0/baseLibrary-2.1.0.pom
Download https://repo1.maven.org/maven2/xml-apis/xml-apis/1.0.b2/xml-apis-1.0.b2.pom
Download https://repo1.maven.org/maven2/com/beust/jcommander/1.35/jcommander-1.35.pom
Download https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/3/oss-parent-3.pom
Download https://repo1.maven.org/maven2/com/android/tools/layoutlib/layoutlib-api/25.1.0/layoutlib-api-25.1.0.pom
Download https://repo1.maven.org/maven2/com/android/tools/dvlib/25.1.0/dvlib-25.1.0.pom
Download https://repo1.maven.org/maven2/com/android/tools/repository/25.1.0/repository-25.1.0.pom
Download https://repo1.maven.org/maven2/com/android/tools/lint/lint-api/25.1.0/lint-api-25.1.0.pom
Download https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.1.0/gradle-2.1.0.jar
Download https://jitpack.io/com/github/alxndrsn/android-check/1f87548c0686d823e5f1490a2053b70bd9f5022e/android-check-1f87548c0686d823e5f1490a2053b70bd9f5022e.jar
Download https://repo1.maven.org/maven2/com/trickyandroid/jacoco-everywhere/0.2.1/jacoco-everywhere-0.2.1.jar
Download https://repo1.maven.org/maven2/com/android/tools/build/gradle-core/2.1.0/gradle-core-2.1.0.jar
Download https://repo1.maven.org/maven2/com/puppycrawl/tools/checkstyle/6.10.1/checkstyle-6.10.1.jar
Download https://repo1.maven.org/maven2/com/google/code/findbugs/findbugs/3.0.1/findbugs-3.0.1.jar
Download https://repo1.maven.org/maven2/net/sourceforge/pmd/pmd-java/5.3.4/pmd-java-5.3.4.jar
Download https://repo1.maven.org/maven2/com/android/tools/build/builder/2.1.0/builder-2.1.0.jar
Download https://repo1.maven.org/maven2/com/android/tools/lint/lint/25.1.0/lint-25.1.0.jar
Download https://repo1.maven.org/maven2/com/android/tools/build/transform-api/2.0.0-deprecated-use-gradle-api/transform-api-2.0.0-deprecated-use-gradle-api.jar
Download https://repo1.maven.org/maven2/com/android/tools/build/gradle-api/2.1.0/gradle-api-2.1.0.jar
Download https://repo1.maven.org/maven2/com/android/databinding/compilerCommon/2.1.0/compilerCommon-2.1.0.jar
Download https://repo1.maven.org/maven2/org/jacoco/org.jacoco.core/0.7.2.201409121644/org.jacoco.core-0.7.2.201409121644.jar
Download https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar
Download https://repo1.maven.org/maven2/antlr/antlr/2.7.7/antlr-2.7.7.jar
Download https://repo1.maven.org/maven2/org/antlr/antlr4-runtime/4.5.1-1/antlr4-runtime-4.5.1-1.jar
Download https://repo1.maven.org/maven2/commons-beanutils/commons-beanutils/1.9.2/commons-beanutils-1.9.2.jar
Download https://repo1.maven.org/maven2/commons-cli/commons-cli/1.3.1/commons-cli-1.3.1.jar
Download https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/2.0.1/jsr305-2.0.1.jar
Download https://repo1.maven.org/maven2/com/google/code/findbugs/bcel-findbugs/6.0/bcel-findbugs-6.0.jar
Download https://repo1.maven.org/maven2/com/google/code/findbugs/jFormatString/2.0.1/jFormatString-2.0.1.jar
Download https://repo1.maven.org/maven2/org/ow2/asm/asm-debug-all/5.0.2/asm-debug-all-5.0.2.jar
Download https://repo1.maven.org/maven2/com/apple/AppleJavaExtensions/1.4/AppleJavaExtensions-1.4.jar
Download https://repo1.maven.org/maven2/jaxen/jaxen/1.1.6/jaxen-1.1.6.jar
Download https://repo1.maven.org/maven2/net/java/dev/javacc/javacc/5.0/javacc-5.0.jar
Download https://repo1.maven.org/maven2/net/sourceforge/pmd/pmd-core/5.3.4/pmd-core-5.3.4.jar
Download https://repo1.maven.org/maven2/net/sourceforge/saxon/saxon/9.1.0.8/saxon-9.1.0.8.jar
Download https://repo1.maven.org/maven2/net/sourceforge/saxon/saxon/9.1.0.8/saxon-9.1.0.8-dom.jar
Download https://repo1.maven.org/maven2/com/android/tools/build/builder-model/2.1.0/builder-model-2.1.0.jar
Download https://repo1.maven.org/maven2/com/android/tools/build/builder-test-api/2.1.0/builder-test-api-2.1.0.jar
Download https://repo1.maven.org/maven2/com/android/tools/sdklib/25.1.0/sdklib-25.1.0.jar
Download https://repo1.maven.org/maven2/com/android/tools/sdk-common/25.1.0/sdk-common-25.1.0.jar
Download https://repo1.maven.org/maven2/com/android/tools/common/25.1.0/common-25.1.0.jar
Download https://repo1.maven.org/maven2/com/android/tools/build/manifest-merger/25.1.0/manifest-merger-25.1.0.jar
Download https://repo1.maven.org/maven2/com/android/tools/ddms/ddmlib/25.1.0/ddmlib-25.1.0.jar
Download https://repo1.maven.org/maven2/com/android/tools/jack/jack-api/0.10.0/jack-api-0.10.0.jar
Download https://repo1.maven.org/maven2/com/android/tools/jill/jill-api/0.10.0/jill-api-0.10.0.jar
Download https://repo1.maven.org/maven2/com/android/tools/lint/lint-checks/25.1.0/lint-checks-25.1.0.jar
Download https://repo1.maven.org/maven2/com/android/tools/annotations/25.1.0/annotations-25.1.0.jar
Download https://repo1.maven.org/maven2/com/android/databinding/baseLibrary/2.1.0/baseLibrary-2.1.0.jar
Download https://repo1.maven.org/maven2/xml-apis/xml-apis/1.0.b2/xml-apis-1.0.b2.jar
Download https://repo1.maven.org/maven2/com/beust/jcommander/1.35/jcommander-1.35.jar
Download https://repo1.maven.org/maven2/com/android/tools/layoutlib/layoutlib-api/25.1.0/layoutlib-api-25.1.0.jar
Download https://repo1.maven.org/maven2/com/android/tools/dvlib/25.1.0/dvlib-25.1.0.jar
Download https://repo1.maven.org/maven2/com/android/tools/repository/25.1.0/repository-25.1.0.jar
Download https://repo1.maven.org/maven2/com/android/tools/lint/lint-api/25.1.0/lint-api-25.1.0.jar
Observed package id 'add-ons;addon-google_apis-google-14' in inconsistent location '/Users/mandric/dev/android-sdk-macosx/add-ons/addon-google_apis-google_inc_-14' (Expected '/Users/mandric/dev/android-sdk-macosx/add-ons/addon-google_apis-google-14')
Observed package id 'system-images;android-10;default;x86' in inconsistent location '/Users/mandric/dev/android-sdk-macosx/system-images/android-10/x86' (Expected '/Users/mandric/dev/android-sdk-macosx/system-images/android-10/default/x86')
Observed package id 'system-images;android-14;default;armeabi-v7a' in inconsistent location '/Users/mandric/dev/android-sdk-macosx/system-images/android-14/armeabi-v7a' (Expected '/Users/mandric/dev/android-sdk-macosx/system-images/android-14/default/armeabi-v7a')
Observed package id 'system-images;android-15;default;armeabi-v7a' in inconsistent location '/Users/mandric/dev/android-sdk-macosx/system-images/android-15/armeabi-v7a' (Expected '/Users/mandric/dev/android-sdk-macosx/system-images/android-15/default/armeabi-v7a')
Observed package id 'system-images;android-16;default;armeabi-v7a' in inconsistent location '/Users/mandric/dev/android-sdk-macosx/system-images/android-16/armeabi-v7a' (Expected '/Users/mandric/dev/android-sdk-macosx/system-images/android-16/default/armeabi-v7a')
Observed package id 'system-images;android-17;default;armeabi-v7a' in inconsistent location '/Users/mandric/dev/android-sdk-macosx/system-images/android-17/armeabi-v7a' (Expected '/Users/mandric/dev/android-sdk-macosx/system-images/android-17/default/armeabi-v7a')
Observed package id 'system-images;android-18;default;armeabi-v7a' in inconsistent location '/Users/mandric/dev/android-sdk-macosx/system-images/android-18/armeabi-v7a' (Expected '/Users/mandric/dev/android-sdk-macosx/system-images/android-18/default/armeabi-v7a')
Observed package id 'system-images;android-18;default;x86' in inconsistent location '/Users/mandric/dev/android-sdk-macosx/system-images/android-18/x86' (Expected '/Users/mandric/dev/android-sdk-macosx/system-images/android-18/default/x86')
Observed package id 'system-images;android-19;default;x86' in inconsistent location '/Users/mandric/dev/android-sdk-macosx/system-images/android-19/x86' (Expected '/Users/mandric/dev/android-sdk-macosx/system-images/android-19/default/x86')
Download https://s3.amazonaws.com/repo.commonsware.com/com/commonsware/cwac/wakeful/1.1.0/wakeful-1.1.0.pom
Download https://repo1.maven.org/maven2/com/google/code/findbugs/annotations/3.0.1/annotations-3.0.1.pom
Download https://s3.amazonaws.com/repo.commonsware.com/com/commonsware/cwac/wakeful/1.1.0/wakeful-1.1.0.aar
Download https://repo1.maven.org/maven2/com/google/code/findbugs/annotations/3.0.1/annotations-3.0.1.jar
Incremental java compilation is an incubating feature.
Download https://repo1.maven.org/maven2/org/robolectric/robolectric/3.1-rc1/robolectric-3.1-rc1.pom
Download https://repo1.maven.org/maven2/org/robolectric/robolectric-parent/3.1-rc1/robolectric-parent-3.1-rc1.pom
Download https://repo1.maven.org/maven2/com/squareup/okhttp3/mockwebserver/3.2.0/mockwebserver-3.2.0.pom
Download https://repo1.maven.org/maven2/com/squareup/okhttp3/parent/3.2.0/parent-3.2.0.pom
Download https://repo1.maven.org/maven2/org/robolectric/robolectric-annotations/3.1-rc1/robolectric-annotations-3.1-rc1.pom
Download https://repo1.maven.org/maven2/org/robolectric/robolectric-resources/3.1-rc1/robolectric-resources-3.1-rc1.pom
Download https://repo1.maven.org/maven2/org/robolectric/robolectric-utils/3.1-rc1/robolectric-utils-3.1-rc1.pom
Download https://repo1.maven.org/maven2/org/robolectric/shadows-core/3.1-rc1/shadows-core-3.1-rc1.pom
Download https://repo1.maven.org/maven2/org/robolectric/robolectric-shadows/3.1-rc1/robolectric-shadows-3.1-rc1.pom
Download https://repo1.maven.org/maven2/org/bouncycastle/bcprov-jdk16/1.46/bcprov-jdk16-1.46.pom
Download https://repo1.maven.org/maven2/org/ow2/asm/asm/5.0.1/asm-5.0.1.pom
Download https://repo1.maven.org/maven2/org/ow2/asm/asm-commons/5.0.1/asm-commons-5.0.1.pom
Download https://repo1.maven.org/maven2/org/ow2/asm/asm-util/5.0.1/asm-util-5.0.1.pom
Download https://repo1.maven.org/maven2/org/ow2/asm/asm-analysis/5.0.1/asm-analysis-5.0.1.pom
Download https://repo1.maven.org/maven2/com/ximpleware/vtd-xml/2.11/vtd-xml-2.11.pom
Download https://repo1.maven.org/maven2/com/thoughtworks/xstream/xstream/1.4.8/xstream-1.4.8.pom
Download https://repo1.maven.org/maven2/com/thoughtworks/xstream/xstream-parent/1.4.8/xstream-parent-1.4.8.pom
Download https://repo1.maven.org/maven2/org/codehaus/codehaus-parent/3/codehaus-parent-3.pom
Download https://repo1.maven.org/maven2/org/apache/maven/maven-ant-tasks/2.1.3/maven-ant-tasks-2.1.3.pom
Download https://repo1.maven.org/maven2/org/apache/ant/ant/1.8.0/ant-1.8.0.pom
Download https://repo1.maven.org/maven2/org/apache/ant/ant-parent/1.8.0/ant-parent-1.8.0.pom
Download https://repo1.maven.org/maven2/com/squareup/okhttp3/okhttp/3.2.0/okhttp-3.2.0.pom
Download https://repo1.maven.org/maven2/com/squareup/okhttp3/okhttp-ws/3.2.0/okhttp-ws-3.2.0.pom
Download https://repo1.maven.org/maven2/com/google/android/apps/common/testing/accessibility/framework/accessibility-test-framework/2.1/accessibility-test-framework-2.1.pom
Download https://repo1.maven.org/maven2/com/ibm/icu/icu4j/53.1/icu4j-53.1.pom
Download https://repo1.maven.org/maven2/com/google/guava/guava/19.0-rc2/guava-19.0-rc2.pom
Download https://repo1.maven.org/maven2/com/google/guava/guava-parent/19.0-rc2/guava-parent-19.0-rc2.pom
Download https://repo1.maven.org/maven2/com/almworks/sqlite4java/sqlite4java/0.282/sqlite4java-0.282.pom
Download https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/4/oss-parent-4.pom
Download https://repo1.maven.org/maven2/org/ow2/asm/asm-tree/5.0.1/asm-tree-5.0.1.pom
Download https://repo1.maven.org/maven2/xmlpull/xmlpull/1.1.3.1/xmlpull-1.1.3.1.pom
Download https://repo1.maven.org/maven2/xpp3/xpp3_min/1.1.4c/xpp3_min-1.1.4c.pom
Download https://repo1.maven.org/maven2/org/apache/ant/ant-launcher/1.8.0/ant-launcher-1.8.0.pom
Download https://repo1.maven.org/maven2/org/hamcrest/hamcrest-library/1.3/hamcrest-library-1.3.pom
Download https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/2.6.1/protobuf-java-2.6.1.pom
Download https://repo1.maven.org/maven2/com/google/google/1/google-1.pom
Download https://repo1.maven.org/maven2/org/robolectric/robolectric-annotations/3.1-rc1/robolectric-annotations-3.1-rc1.jar
Download https://repo1.maven.org/maven2/org/ow2/asm/asm/5.0.1/asm-5.0.1.jar
Download https://repo1.maven.org/maven2/org/ow2/asm/asm-tree/5.0.1/asm-tree-5.0.1.jar
Download https://repo1.maven.org/maven2/org/ow2/asm/asm-commons/5.0.1/asm-commons-5.0.1.jar
Download https://repo1.maven.org/maven2/org/hamcrest/hamcrest-library/1.3/hamcrest-library-1.3.jar
Download https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/2.6.1/protobuf-java-2.6.1.jar
Download https://repo1.maven.org/maven2/com/google/android/apps/common/testing/accessibility/framework/accessibility-test-framework/2.1/accessibility-test-framework-2.1.jar
Download https://repo1.maven.org/maven2/org/robolectric/robolectric-utils/3.1-rc1/robolectric-utils-3.1-rc1.jar
Download https://repo1.maven.org/maven2/com/ximpleware/vtd-xml/2.11/vtd-xml-2.11.jar
Download https://repo1.maven.org/maven2/org/robolectric/robolectric-resources/3.1-rc1/robolectric-resources-3.1-rc1.jar
Download https://repo1.maven.org/maven2/com/ibm/icu/icu4j/53.1/icu4j-53.1.jar
Download https://repo1.maven.org/maven2/com/google/guava/guava/19.0-rc2/guava-19.0-rc2.jar
Download https://repo1.maven.org/maven2/com/almworks/sqlite4java/sqlite4java/0.282/sqlite4java-0.282.jar
Download https://repo1.maven.org/maven2/org/robolectric/shadows-core/3.1-rc1/shadows-core-3.1-rc1.jar
Download https://repo1.maven.org/maven2/org/bouncycastle/bcprov-jdk16/1.46/bcprov-jdk16-1.46.jar
Download https://repo1.maven.org/maven2/org/ow2/asm/asm-util/5.0.1/asm-util-5.0.1.jar
Download https://repo1.maven.org/maven2/org/ow2/asm/asm-analysis/5.0.1/asm-analysis-5.0.1.jar
Download https://repo1.maven.org/maven2/xmlpull/xmlpull/1.1.3.1/xmlpull-1.1.3.1.jar
Download https://repo1.maven.org/maven2/xpp3/xpp3_min/1.1.4c/xpp3_min-1.1.4c.jar
Download https://repo1.maven.org/maven2/com/thoughtworks/xstream/xstream/1.4.8/xstream-1.4.8.jar
Download https://repo1.maven.org/maven2/org/apache/maven/maven-ant-tasks/2.1.3/maven-ant-tasks-2.1.3.jar
Download https://repo1.maven.org/maven2/org/apache/ant/ant-launcher/1.8.0/ant-launcher-1.8.0.jar
Download https://repo1.maven.org/maven2/org/apache/ant/ant/1.8.0/ant-1.8.0.jar
Download https://repo1.maven.org/maven2/org/robolectric/robolectric/3.1-rc1/robolectric-3.1-rc1.jar
Download https://repo1.maven.org/maven2/com/squareup/okhttp3/okhttp/3.2.0/okhttp-3.2.0.jar
Download https://repo1.maven.org/maven2/com/squareup/okhttp3/okhttp-ws/3.2.0/okhttp-ws-3.2.0.jar
Download https://repo1.maven.org/maven2/com/squareup/okhttp3/mockwebserver/3.2.0/mockwebserver-3.2.0.jar
Download https://repo1.maven.org/maven2/com/squareup/javawriter/2.1.1/javawriter-2.1.1.pom
Download https://repo1.maven.org/maven2/org/hamcrest/hamcrest-integration/1.3/hamcrest-integration-1.3.pom
Download https://repo1.maven.org/maven2/javax/annotation/javax.annotation-api/1.2/javax.annotation-api-1.2.pom
Download https://repo1.maven.org/maven2/net/java/jvnet-parent/3/jvnet-parent-3.pom
Download https://repo1.maven.org/maven2/com/squareup/javawriter/2.1.1/javawriter-2.1.1.jar
Download https://repo1.maven.org/maven2/org/hamcrest/hamcrest-integration/1.3/hamcrest-integration-1.3.jar
Download https://repo1.maven.org/maven2/javax/annotation/javax.annotation-api/1.2/javax.annotation-api-1.2.jar
Download https://repo1.maven.org/maven2/org/jacoco/org.jacoco.agent/0.7.2.201409121644/org.jacoco.agent-0.7.2.201409121644.pom
Download https://repo1.maven.org/maven2/org/jacoco/org.jacoco.agent/0.7.2.201409121644/org.jacoco.agent-0.7.2.201409121644.jar
:preBuild UP-TO-DATE
:preDebugBuild UP-TO-DATE
:checkDebugManifest
:preReleaseBuild UP-TO-DATE
:prepareComAndroidSupportSupportV42301Library
:prepareComCommonswareCwacWakeful110Library
:prepareDebugDependencies
:compileDebugAidl
:compileDebugRenderscript
:generateDebugBuildConfig
:mergeDebugShaders
:compileDebugShaders
:generateDebugAssets
:mergeDebugAssets
:generateDebugResValues
:generateDebugResources
:mergeDebugResources
:processDebugManifest
:processDebugResources
:generateDebugSources
:incrementalDebugJavaCompilationSafeguard
:compileDebugJavaWithJavac
:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/Users/mandric/dev/medic-gateway/src/main/java/medic/gateway/SmsCompatibility.java:51: warning: [deprecation] createFromPdu(byte[]) in SmsMessage has been deprecated
> Building 56% > :compilreturn SmsMessage.createFromPdu(pdu);
			                 ^
1 warning
:compileDebugNdk UP-TO-DATE
:compileDebugSources
:prePackageMarkerForDebug
:unzipJacocoAgent
:transformClassesWithJacocoForDebug
:transformClassesWithDexForDebug
To run dex in process, the Gradle daemon needs a larger heap.
It currently has approximately 910 MB.
For faster builds, increase the maximum heap size for the Gradle daemon to more than 2048 MB.
To do this set org.gradle.jvmargs=-Xmx2048M in the project gradle.properties.
For more information see https://docs.gradle.org/current/userguide/build_environment.html
:mergeDebugJniLibFolders
:transformNative_libsWithMergeJniLibsForDebug
:processDebugJavaRes UP-TO-DATE
:transformResourcesWithMergeJavaResForDebug
:validateDebugSigning
:packageDebug
:zipalignDebug
:assembleDebug
:installDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':installDebug'.
> com.android.builder.testing.api.DeviceException: No connected devices!

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':installDebug'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:68)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: org.gradle.internal.UncheckedException: com.android.builder.testing.api.DeviceException: No connected devices!
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:45)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:78)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:228)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 14 more
Caused by: com.android.builder.testing.api.DeviceException: No connected devices!
	at com.android.builder.testing.ConnectedDeviceProvider.init(ConnectedDeviceProvider.java:116)
	at com.android.build.gradle.internal.tasks.InstallVariantTask.install(InstallVariantTask.java:99)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	... 21 more


BUILD FAILED

Total time: 6 mins 42.999 secs
make: *** [deploy] Error 1
```

**Comment by mandric** [comment]
Or maybe better question is why is a connected device required to run a build?

**Comment by alxndrsn** [comment]
You need a connected device or emulator running to run the tests.
