### ISSUE TITLE
Cannot save settings on first-run if _Enable polling_ is unchecked and URL is invalid

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-gateway#36]
```D/MedicGateway( 4230): SettingsDialogActivity.saveSettings()
D/MedicGateway( 4230): medic.gateway.alert.IllegalSettingsException: component[2131427344]: error[2131296273]
D/MedicGateway( 4230): 	at medic.gateway.alert.Settings.validate(SettingsStore.java:94)
D/MedicGateway( 4230): 	at medic.gateway.alert.SettingsStore.save(SettingsStore.java:40)
D/MedicGateway( 4230): 	at medic.gateway.alert.SettingsDialogActivity.saveSettings(SettingsDialogActivity.java:126)
D/MedicGateway( 4230): 	at medic.gateway.alert.SettingsDialogActivity.access$000(SettingsDialogActivity.java:19)
D/MedicGateway( 4230): 	at medic.gateway.alert.SettingsDialogActivity$2.doInBackground(SettingsDialogActivity.java:111)
D/MedicGateway( 4230): 	at medic.gateway.alert.SettingsDialogActivity$2.doInBackground(SettingsDialogActivity.java:109)
D/MedicGateway( 4230): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
D/MedicGateway( 4230): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
D/MedicGateway( 4230): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
D/MedicGateway( 4230): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
D/MedicGateway( 4230): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
D/MedicGateway( 4230): 	at java.lang.Thread.run(Thread.java:848)
E/AndroidRuntime( 4230): FATAL EXCEPTION: AsyncTask #1
E/AndroidRuntime( 4230): Process: medic.gateway.alert, PID: 4230
E/AndroidRuntime( 4230): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime( 4230): 	at android.os.AsyncTask$3.done(AsyncTask.java:300)
E/AndroidRuntime( 4230): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
E/AndroidRuntime( 4230): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
E/AndroidRuntime( 4230): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime( 4230): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
E/AndroidRuntime( 4230): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime( 4230): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime( 4230): 	at java.lang.Thread.run(Thread.java:848)
E/AndroidRuntime( 4230): Caused by: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
E/AndroidRuntime( 4230): 	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6728)
E/AndroidRuntime( 4230): 	at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:1011)
E/AndroidRuntime( 4230): 	at android.view.ViewGroup.invalidateChild(ViewGroup.java:4552)
E/AndroidRuntime( 4230): 	at android.view.View.invalidate(View.java:11095)
E/AndroidRuntime( 4230): 	at android.view.View.invalidate(View.java:11044)
E/AndroidRuntime( 4230): 	at android.widget.Editor.setErrorIcon(Editor.java:339)
E/AndroidRuntime( 4230): 	at android.widget.Editor.setError(Editor.java:324)
E/AndroidRuntime( 4230): 	at android.widget.TextView.setError(TextView.java:4504)
E/AndroidRuntime( 4230): 	at android.widget.TextView.setError(TextView.java:4489)
E/AndroidRuntime( 4230): 	at medic.gateway.alert.SettingsDialogActivity.showError(SettingsDialogActivity.java:186)
E/AndroidRuntime( 4230): 	at medic.gateway.alert.SettingsDialogActivity.showError(SettingsDialogActivity.java:181)
E/AndroidRuntime( 4230): 	at medic.gateway.alert.SettingsDialogActivity.saveSettings(SettingsDialogActivity.java:132)
E/AndroidRuntime( 4230): 	at medic.gateway.alert.SettingsDialogActivity.access$000(SettingsDialogActivity.java:19)
E/AndroidRuntime( 4230): 	at medic.gateway.alert.SettingsDialogActivity$2.doInBackground(SettingsDialogActivity.java:111)
E/AndroidRuntime( 4230): 	at medic.gateway.alert.SettingsDialogActivity$2.doInBackground(SettingsDialogActivity.java:109)
E/AndroidRuntime( 4230): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
E/AndroidRuntime( 4230): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime( 4230): 	... 4 more```

**Comment by alxndrsn** [comment]
Fixed by recent changes.
