### ISSUE TITLE
When device space runs out, app explodes

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-gateway#44]
This should probably be a trigger for some cleanup:

```
 I/MedicGateway(29271): Could not write log entry to DB.
 I/MedicGateway(29271): android.database.sqlite.SQLiteFullException: database or disk is full (code 13): , while compiling: PRAGMA journal_mode
 I/MedicGateway(29271):  at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
 I/MedicGateway(29271):  at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:893)
 I/MedicGateway(29271):  at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:638)
 I/MedicGateway(29271):  at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:320)
 I/MedicGateway(29271):  at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:294)
 I/MedicGateway(29271):  at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:215)
 I/MedicGateway(29271):  at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
 I/MedicGateway(29271):  at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
 I/MedicGateway(29271):  at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
 I/MedicGateway(29271):  at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
 I/MedicGateway(29271):  at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:829)
 I/MedicGateway(29271):  at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:814)
 I/MedicGateway(29271):  at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:709)
 I/MedicGateway(29271):  at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1040)
 I/MedicGateway(29271):  at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:256)
 I/MedicGateway(29271):  at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:224)
 I/MedicGateway(29271):  at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
 I/MedicGateway(29271):  at medic.gateway.alert.c.<init>(Unknown Source)
 I/MedicGateway(29271):  at medic.gateway.alert.c.a(Unknown Source)
 I/MedicGateway(29271):  at medic.gateway.alert.i.a(Unknown Source)
 I/MedicGateway(29271):  at medic.gateway.alert.i.a(Unknown Source)
 I/MedicGateway(29271):  at medic.gateway.alert.i.a(Unknown Source)
 I/MedicGateway(29271):  at medic.gateway.alert.i.a(Unknown Source)
 I/MedicGateway(29271):  at medic.gateway.alert.i.a(Unknown Source)
...
```

**Comment by alxndrsn** [comment]
Looks like this is in a log loop, because it's trying to write each out of memory/db-write error to the database.

**Comment by alxndrsn** [comment]
Further logs:

```
I/MedicGateway(32421): Exception caught trying to send SMSes: database or disk is full (code 13)
 I/MedicGateway(32421): android.database.sqlite.SQLiteFullException: database or disk is full (code 13)
 I/MedicGateway(32421):  at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
 I/MedicGateway(32421):  at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:849)
 I/MedicGateway(32421):  at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
 I/MedicGateway(32421):  at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
 I/MedicGateway(32421):  at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:162)
 I/MedicGateway(32421):  at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:151)
 I/MedicGateway(32421):  at medic.gateway.alert.c.a(Unknown Source)
 I/MedicGateway(32421):  at medic.gateway.alert.ad.a(Unknown Source)
 I/MedicGateway(32421):  at medic.gateway.alert.WakefulService.a(Unknown Source)
 I/MedicGateway(32421):  at com.commonsware.cwac.wakeful.a.onHandleIntent(Unknown Source)
 I/MedicGateway(32421):  at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
 I/MedicGateway(32421):  at android.os.Handler.dispatchMessage(Handler.java:110)
 I/MedicGateway(32421):  at android.os.Looper.loop(Looper.java:193)
 I/MedicGateway(32421):  at android.os.HandlerThread.run(HandlerThread.java:61)
 E/AndroidRuntime(32421): FATAL EXCEPTION: main
 E/AndroidRuntime(32421): Process: medic.gateway.alert, PID: 32421
 E/AndroidRuntime(32421): android.database.sqlite.SQLiteFullException: database or disk is full (code 13)
 E/AndroidRuntime(32421):        at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
 E/AndroidRuntime(32421):        at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:849)
 E/AndroidRuntime(32421):        at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
 E/AndroidRuntime(32421):        at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
 E/AndroidRuntime(32421):        at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:162)
 E/AndroidRuntime(32421):        at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:151)
 E/AndroidRuntime(32421):        at a.a.a.f.a.getCount(Unknown Source)
 E/AndroidRuntime(32421):        at android.widget.AdapterView$AdapterDataSetObserver.onChanged(AdapterView.java:802)
 E/AndroidRuntime(32421):        at android.widget.AbsListView$AdapterDataSetObserver.onChanged(AbsListView.java:6676)
 E/AndroidRuntime(32421):        at android.database.DataSetObservable.notifyChanged(DataSetObservable.java:37)
 E/AndroidRuntime(32421):        at android.widget.BaseAdapter.notifyDataSetChanged(BaseAdapter.java:50)
 E/AndroidRuntime(32421):        at a.a.a.f.a.b(Unknown Source)
 E/AndroidRuntime(32421):        at medic.gateway.alert.GatewayEventLogFragment.a(Unknown Source)
 E/AndroidRuntime(32421):        at a.a.a.a.az.b(Unknown Source)
 E/AndroidRuntime(32421):        at a.a.a.a.az.a(Unknown Source)
 E/AndroidRuntime(32421):        at a.a.a.b.i.b(Unknown Source)
 E/AndroidRuntime(32421):        at a.a.a.b.h.a(Unknown Source)
 E/AndroidRuntime(32421):        at a.a.a.b.h.b(Unknown Source)
 E/AndroidRuntime(32421):        at a.a.a.b.b.a(Unknown Source)
 E/AndroidRuntime(32421):        at a.a.a.b.m.c(Unknown Source)
 E/AndroidRuntime(32421):        at a.a.a.b.s.handleMessage(Unknown Source)
 E/AndroidRuntime(32421):        at android.os.Handler.dispatchMessage(Handler.java:110)
 E/AndroidRuntime(32421):        at android.os.Looper.loop(Looper.java:193)
 E/AndroidRuntime(32421):        at android.app.ActivityThread.main(ActivityThread.java:5299)
 E/AndroidRuntime(32421):        at java.lang.reflect.Method.invokeNative(Native Method)
 E/AndroidRuntime(32421):        at java.lang.reflect.Method.invoke(Method.java:515)
 E/AndroidRuntime(32421):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:830)
 E/AndroidRuntime(32421):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:646)
 E/AndroidRuntime(32421):        at dalvik.system.NativeStart.main(Native Method)
 E/AndroidRuntime(29001): FATAL EXCEPTION: AsyncTask #2
 E/AndroidRuntime(29001): Process: com.google.android.gm, PID: 29001
 E/AndroidRuntime(29001): java.lang.RuntimeException: An error occured while executing doInBackground()
 E/AndroidRuntime(29001):        at android.os.AsyncTask$3.done(AsyncTask.java:300)
 E/AndroidRuntime(29001):        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
 E/AndroidRuntime(29001):        at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
 E/AndroidRuntime(29001):        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
 E/AndroidRuntime(29001):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
 E/AndroidRuntime(29001):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
 E/AndroidRuntime(29001):        at java.lang.Thread.run(Thread.java:848)
 E/AndroidRuntime(29001): Caused by: android.database.sqlite.SQLiteFullException: database or disk is full (code 13)
 E/AndroidRuntime(29001):        at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
 E/AndroidRuntime(29001):        at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:738)
 E/AndroidRuntime(29001):        at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
 E/AndroidRuntime(29001):        at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
 E/AndroidRuntime(29001):        at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1699)
 E/AndroidRuntime(29001):        at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1628)
 E/AndroidRuntime(29001):        at bgv.onOpen(SourceFile:1357)
 E/AndroidRuntime(29001):        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:267)
 E/AndroidRuntime(29001):        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
 E/AndroidRuntime(29001):        at com.android.email.provider.EmailProvider.a(SourceFile:767)
 E/AndroidRuntime(29001):        at com.android.email.provider.EmailProvider.i(SourceFile:1588)
 E/AndroidRuntime(29001):        at com.android.email.provider.EmailProvider.b(SourceFile:580)
 E/AndroidRuntime(29001):        at com.android.email.provider.EmailProvider.query(SourceFile:1861)
 E/AndroidRuntime(29001):        at android.content.ContentProvider.query(ContentProvider.java:922)
 E/AndroidRuntime(29001):        at android.content.ContentProvider$Transport.query(ContentProvider.java:213)
 E/AndroidRuntime(29001):        at android.content.ContentResolver.query(ContentResolver.java:462)
 E/AndroidRuntime(29001):        at android.content.CursorLoader.loadInBackground(CursorLoader.java:65)
 E/AndroidRuntime(29001):        at android.content.CursorLoader.loadInBackground(CursorLoader.java:43)
 E/AndroidRuntime(29001):        at android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:312)
 E/AndroidRuntime(29001):        at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:69)
 E/AndroidRuntime(29001):        at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:57)
```

**Comment by alxndrsn** [comment]
Looks like that all started here:
```
I/MedicGateway(32421): IntentProcessor.onReceive() :: android.provider.Telephony.SMS_DELIVER
 I/MedicGateway(32421): Exception caught trying to poll webapp: database or disk is full (code 13)
 I/MedicGateway(32421): android.database.sqlite.SQLiteFullException: database or disk is full (code 13)
 I/MedicGateway(32421):  at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
 I/MedicGateway(32421):  at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:849)
 I/MedicGateway(32421):  at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
 I/MedicGateway(32421):  at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
 I/MedicGateway(32421):  at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:162)
 I/MedicGateway(32421):  at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:151)
 I/MedicGateway(32421):  at medic.gateway.alert.c.d(Unknown Source)
 I/MedicGateway(32421):  at medic.gateway.alert.c.a(Unknown Source)
 I/MedicGateway(32421):  at medic.gateway.alert.WakefulService.a(Unknown Source)
 I/MedicGateway(32421):  at com.commonsware.cwac.wakeful.a.onHandleIntent(Unknown Source)
 I/MedicGateway(32421):  at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
 I/MedicGateway(32421):  at android.os.Handler.dispatchMessage(Handler.java:110)
 I/MedicGateway(32421):  at android.os.Looper.loop(Looper.java:193)
 I/MedicGateway(32421):  at android.os.HandlerThread.run(HandlerThread.java:61)
 I/MedicGateway(32421): Failed to save received SMS to db: com.android.internal.telephony.GeminiSmsMessage@41f16290
 I/MedicGateway(32421): Exception caught trying to send SMSes: database or disk is full (code 13)
 I/MedicGateway(32421): android.database.sqlite.SQLiteFullException: database or disk is full (code 13)
 I/MedicGateway(32421):  at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
 I/MedicGateway(32421):  at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:849)
 I/MedicGateway(32421):  at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
 I/MedicGateway(32421):  at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
 I/MedicGateway(32421):  at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:162)
 I/MedicGateway(32421):  at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:151)
 I/MedicGateway(32421):  at medic.gateway.alert.c.a(Unknown Source)
 I/MedicGateway(32421):  at medic.gateway.alert.ad.a(Unknown Source)
 I/MedicGateway(32421):  at medic.gateway.alert.WakefulService.a(Unknown Source)
 I/MedicGateway(32421):  at com.commonsware.cwac.wakeful.a.onHandleIntent(Unknown Source)
 I/MedicGateway(32421):  at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
 I/MedicGateway(32421):  at android.os.Handler.dispatchMessage(Handler.java:110)
 I/MedicGateway(32421):  at android.os.Looper.loop(Looper.java:193)
 I/MedicGateway(32421):  at android.os.HandlerThread.run(HandlerThread.java:61)
```
