### ISSUE TITLE
Server is not corrected when it sends a duplicate message

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-gateway#50]
```
03-03 11:12:14.259 25881 28861 I MedicGateway: Saving WO message: {"id":"xxx-yyy","to":"+123123123","content":"नमस्ते! Bilbo Baggins ले Frodo (12345) लाई आँखा जाँचको लागि पठाउनु भएको छैन। कृपया सोधखोज गर्नु होला। धन्यवाद!"}
03-03 11:12:14.259 25881 28861 I MedicGateway: Failed to save WO message: {"id":"xxx-yyy","to":"+123123123","content":"नमस्ते! Bilbo Baggins ले Frodo (12345) लाई आँखा जाँचको लागि पठाउनु भएको छैन। कृपया सोधखोज गर्नु होला। धन्यवाद!"}```

**Comment by alxndrsn** [comment]
This does not seem to be a specific issue with the content of a particular message.

**Comment by alxndrsn** [comment]
Exception:
```
03-06 08:38:32.542  7222 30495 I MedicGateway: Saving WO message: {"id":"abc","to":"+123","content":"hello"}
03-06 08:38:32.542  7222 30495 D MedicGateway: medic.gateway.alert.Db :: store() :: WoMessage@abc-UNSENT
03-06 08:38:32.542  7222 30495 W MedicGateway: Exception writing WoMessage to db: WoMessage@abc-UNSENT
03-06 08:38:32.542  7222 30495 W MedicGateway: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: wo_message._id (code 1555)
03-06 08:38:32.542  7222 30495 W MedicGateway: #################################################################
03-06 08:38:32.542  7222 30495 W MedicGateway: Error Code : 1555 (SQLITE_CONSTRAINT_PRIMARYKEY)
03-06 08:38:32.542  7222 30495 W MedicGateway: Caused By : Abort due to constraint violation.
03-06 08:38:32.542  7222 30495 W MedicGateway: 	(UNIQUE constraint failed: wo_message._id (code 1555))
03-06 08:38:32.542  7222 30495 W MedicGateway: #################################################################
03-06 08:38:32.542  7222 30495 W MedicGateway: 	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
03-06 08:38:32.542  7222 30495 W MedicGateway: 	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:915)
03-06 08:38:32.542  7222 30495 W MedicGateway: 	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
03-06 08:38:32.542  7222 30495 W MedicGateway: 	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
03-06 08:38:32.542  7222 30495 W MedicGateway: 	at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1609)
03-06 08:38:32.542  7222 30495 W MedicGateway: 	at android.database.sqlite.SQLiteDatabase.insertOrThrow(SQLiteDatabase.java:1505)
03-06 08:38:32.542  7222 30495 W MedicGateway: 	at medic.gateway.alert.Db.store(Db.java:176)
03-06 08:38:32.542  7222 30495 W MedicGateway: 	at medic.gateway.alert.WebappPoller.saveMessage(WebappPoller.java:99)
03-06 08:38:32.542  7222 30495 W MedicGateway: 	at medic.gateway.alert.WebappPoller.handleJsonResponse(WebappPoller.java:75)
03-06 08:38:32.542  7222 30495 W MedicGateway: 	at medic.gateway.alert.WebappPoller.pollWebapp(WebappPoller.java:44)
03-06 08:38:32.542  7222 30495 W MedicGateway: 	at medic.gateway.alert.WakefulService.doWakefulWork(WakefulService.java:23)
03-06 08:38:32.542  7222 30495 W MedicGateway: 	at com.commonsware.cwac.wakeful.WakefulIntentService.onHandleIntent(WakefulIntentService.java:110)
03-06 08:38:32.542  7222 30495 W MedicGateway: 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
03-06 08:38:32.542  7222 30495 W MedicGateway: 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-06 08:38:32.542  7222 30495 W MedicGateway: 	at android.os.Looper.loop(Looper.java:148)
03-06 08:38:32.542  7222 30495 W MedicGateway: 	at android.os.HandlerThread.run(HandlerThread.java:61)
03-06 08:38:32.552  7222 30495 I MedicGateway: Failed to save WO message: {"id":"abc","to":"+123","content":"hello"}
```
If this means that the message has already been received by the gateway, but webapp still has it in the `pending` state, then we need to make sure that we:
*  catch the insert fail, and
* log it, comparing the content of the message to be saved and the message in the db
* update the message so that its status is echoed back to the server next time
