### ISSUE TITLE
Clicking retry when viewing details of FAILED message -> crash

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-gateway#55]
v0.4.0
```
 E/AndroidRuntime(29654): FATAL EXCEPTION: main
 E/AndroidRuntime(29654): Process: medic.gateway.alert, PID: 29654
 E/AndroidRuntime(29654): java.lang.NullPointerException
 E/AndroidRuntime(29654):        at medic.gateway.alert.af.a(Unknown Source)
 E/AndroidRuntime(29654):        at medic.gateway.alert.WoListFragment.a(Unknown Source)
 E/AndroidRuntime(29654):        at medic.gateway.alert.ap.onClick(Unknown Source)
 E/AndroidRuntime(29654):        at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)
 E/AndroidRuntime(29654):        at android.os.Handler.dispatchMessage(Handler.java:110)
 E/AndroidRuntime(29654):        at android.os.Looper.loop(Looper.java:193)
 E/AndroidRuntime(29654):        at android.app.ActivityThread.main(ActivityThread.java:5299)
 E/AndroidRuntime(29654):        at java.lang.reflect.Method.invokeNative(Native Method)
 E/AndroidRuntime(29654):        at java.lang.reflect.Method.invoke(Method.java:515)
 E/AndroidRuntime(29654):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:830)
 E/AndroidRuntime(29654):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:646)
 E/AndroidRuntime(29654):        at dalvik.system.NativeStart.main(Native Method)
```

**Comment by alxndrsn** [comment]
Does not happen on `master`.
