### ISSUE TITLE
Retrying a FAILED WO message from detail dialog crashes app

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-gateway#73]
```
03-15 12:52:42.989 14750 14750 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
03-15 12:52:42.989 14750 14750 E AndroidRuntime: 	at medic.gateway.alert.ai.a(Unknown Source)
03-15 12:52:42.989 14750 14750 E AndroidRuntime: 	at medic.gateway.alert.WoListFragment.a(Unknown Source)
03-15 12:52:42.989 14750 14750 E AndroidRuntime: 	at medic.gateway.alert.at.onClick(Unknown Source)
03-15 12:52:42.989 14750 14750 E AndroidRuntime: 	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:175)
03-15 12:52:42.989 14750 14750 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-15 12:52:42.989 14750 14750 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
03-15 12:52:42.989 14750 14750 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7223)
03-15 12:52:42.989 14750 14750 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-15 12:52:42.989 14750 14750 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
03-15 12:52:42.989 14750 14750 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by alxndrsn** [comment]
Cannot recreate.  cc @bishwas-medic
