### ISSUE TITLE
NPE when retrying WtMessage

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-gateway#81]
```
E/AndroidRuntime( 5765): java.lang.NullPointerException
E/AndroidRuntime( 5765):        at medic.gateway.alert.Utils.setText(Utils.java:192)
E/AndroidRuntime( 5765):        at medic.gateway.alert.WtListFragment.retry(WtListFragment.java:124)
E/AndroidRuntime( 5765):        at medic.gateway.alert.WtListFragment$1.onClick(WtListFragment.java:101)
E/AndroidRuntime( 5765):        at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:180)
E/AndroidRuntime( 5765):        at android.os.Handler.dispatchMessage(Handler.java:110)
E/AndroidRuntime( 5765):        at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime( 5765):        at android.app.ActivityThread.main(ActivityThread.java:5299)
E/AndroidRuntime( 5765):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 5765):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 5765):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
E/AndroidRuntime( 5765):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
E/AndroidRuntime( 5765):        at dalvik.system.NativeStart.main(Native Method)
```

This was post-merge of #76

**Comment by alxndrsn** [comment]
Looks like there was no item in the list at the expected index.  Weird!

**Comment by alxndrsn** [comment]
Steps to recreate:
1. scroll down the list 1 whole screen
2. click on a failed message to open its dialog
3. click RETRY
4. BOOM!

**Comment by alxndrsn** [comment]
Can also be recreated on Wo list.
